//! The byte-valued enums of the v1 tables, with Sony's own names.
//!
//! Each one is generated by `byte_enum!`: the named values, and a catch-all variant for a
//! byte nobody named. Variants are documented by their wire value; the names are Sony's.

byte_enum! {
    /// `CommonStatus`, the status byte of every `*_STATUS` message.
    ///
    /// **`00` is `Enable`.** `01` is `Disable`. It is easy to read backwards.
    pub enum CommonStatus, Unknown {
        Enable = 0x00,
        Disable = 0x01,
        OutOfRange = 0xff,
    }
}

byte_enum! {
    /// `CommonOnOffSettingValue`.
    pub enum OnOff, Unknown {
        Off = 0x00,
        On = 0x01,
    }
}

byte_enum! {
    /// `FunctionType`: what the headset lists in its `07` reply. That list is the
    /// capability model; an unknown byte is `NO_USE` in Sony's app and
    /// [`Unknown`](Self::Unknown) here.
    pub enum FunctionType, Unknown {
        BatteryLevel = 0x11,
        UpscalingIndicator = 0x12,
        CodecIndicator = 0x13,
        BleSetup = 0x14,
        LeftRightBatteryLevel = 0x15,
        LeftRightConnectionStatus = 0x17,
        CradleBatteryLevel = 0x18,
        PowerOff = 0x21,
        ConciergeData = 0x22,
        TandemKeepAlive = 0x23,
        FwUpdate = 0x30,
        PairingDeviceManagementClassicBt = 0x38,
        VoiceGuidance = 0x39,
        Vpt = 0x41,
        SoundPosition = 0x42,
        PresetEq = 0x51,
        Ebb = 0x52,
        PresetEqNoncustomizable = 0x53,
        NoiseCancelling = 0x61,
        NoiseCancellingAndAmbientSoundMode = 0x62,
        AmbientSoundMode = 0x63,
        AutoNcAsm = 0x71,
        NcOptimizer = 0x81,
        VibratorAlertNotification = 0x92,
        PlaybackController = 0xa1,
        TrainingMode = 0xb1,
        ActionLogNotifier = 0xc1,
        GeneralSetting1 = 0xd1,
        GeneralSetting2 = 0xd2,
        GeneralSetting3 = 0xd3,
        ConnectionMode = 0xe1,
        Upscaling = 0xe2,
        Vibrator = 0xf1,
        PowerSavingMode = 0xf2,
        ControlByWearing = 0xf3,
        AutoPowerOff = 0xf4,
        SmartTalkingMode = 0xf5,
        AssignableSettings = 0xf6,
    }
}

byte_enum! {
    /// `BatteryChargingStatus`. Sony's own `UNKNOWN` is `F0`.
    pub enum BatteryChargingStatus, Other {
        NotCharging = 0x00,
        Charging = 0x01,
        Unknown = 0xf0,
    }
}

byte_enum! {
    /// `AudioCodec`. Sony's own `OTHER` is `FF`.
    pub enum AudioCodec, Unknown {
        Unsettled = 0x00,
        Sbc = 0x01,
        Aac = 0x02,
        Ldac = 0x10,
        AptX = 0x20,
        AptXHd = 0x21,
        Other = 0xff,
    }
}

byte_enum! {
    /// `UpscalingEffectType`: which flavour of DSEE the headset has.
    pub enum UpscalingEffectType, Unknown {
        DseeHx = 0x00,
        Dsee = 0x01,
        DseeHxAi = 0x02,
    }
}

byte_enum! {
    /// `UpscalingEffectStatus`: whether DSEE is active right now (read-only).
    pub enum UpscalingEffectStatus, Unknown {
        Off = 0x00,
        Valid = 0x01,
        Invalid = 0x02,
    }
}

byte_enum! {
    /// The `00`/`01` of the left/right connection status: not connected, connected.
    pub enum ConnectionState, Unknown {
        NotConnected = 0x00,
        Connected = 0x01,
    }
}

byte_enum! {
    /// `NcAsmInquiredType`, the byte after the command id in the NC/ASM group.
    pub enum NcAsmInquiredType, Unknown {
        NoiseCancelling = 0x01,
        NoiseCancellingAndAmbientSoundMode = 0x02,
        AmbientSoundMode = 0x03,
    }
}

byte_enum! {
    /// `NcAsmEffect`. **`ADJUSTMENT_IN_PROGRESS` is `10` and `ADJUSTMENT_COMPLETION` is
    /// `11`**: `11` is not "on" (a point the community write-ups get wrong).
    pub enum NcAsmEffect, Unknown {
        Off = 0x00,
        On = 0x01,
        AdjustmentInProgress = 0x10,
        AdjustmentCompletion = 0x11,
    }
}

byte_enum! {
    /// `NcAsmSettingType`: how the headset's noise-cancelling control is shaped. The XM4 is
    /// presumed to be `DualSingleOff`, not verified.
    pub enum NcAsmSettingType, Unknown {
        OnOff = 0x00,
        LevelAdjustment = 0x01,
        DualSingleOff = 0x02,
    }
}

byte_enum! {
    /// `NcDualSingleValue`, byte 4 of the NC/ASM parameter when the setting type is
    /// `DualSingleOff`: `Dual` is full noise cancelling, `Single` the community's "wind
    /// noise reduction". With another setting type the byte means something else, and
    /// [`raw`](Self::raw) is how to read it.
    pub enum NcDualSingleValue, Unknown {
        Off = 0x00,
        Single = 0x01,
        Dual = 0x02,
    }
}

byte_enum! {
    /// `AsmSettingType`: ambient sound as an on/off switch or as a level.
    pub enum AsmSettingType, Unknown {
        OnOff = 0x00,
        LevelAdjustment = 0x01,
    }
}

byte_enum! {
    /// `AsmId`: which ambient mode a level belongs to.
    pub enum AsmId, Unknown {
        Normal = 0x00,
        Voice = 0x01,
    }
}

byte_enum! {
    /// `EqEbbInquiredType`, the byte after the command id in the EQ/Extra Bass group.
    pub enum EqEbbInquiredType, Unknown {
        PresetEq = 0x01,
        Ebb = 0x02,
        PresetEqNoncustomizable = 0x03,
    }
}

byte_enum! {
    /// `EqPresetId`. Which of them the XM4 has is what its `51` capability lists. Sony's app
    /// reads an unknown byte as `Off`; this keeps it.
    pub enum EqPresetId, Unknown {
        Off = 0x00,
        Rock = 0x01,
        Pop = 0x02,
        Jazz = 0x03,
        Dance = 0x04,
        Edm = 0x05,
        RAndBHipHop = 0x06,
        Acoustic = 0x07,
        Bright = 0x10,
        Excited = 0x11,
        Mellow = 0x12,
        Relaxed = 0x13,
        Vocal = 0x14,
        Treble = 0x15,
        Bass = 0x16,
        Speech = 0x17,
        Custom = 0xa0,
        UserSetting1 = 0xa1,
        UserSetting2 = 0xa2,
        UserSetting3 = 0xa3,
        UserSetting4 = 0xa4,
        UserSetting5 = 0xa5,
        Unspecified = 0xff,
    }
}

byte_enum! {
    /// `EqBandInformationType`, the kind of one entry of the `5B` extended-info reply.
    /// `Hz` and `Khz` carry the band's centre frequency; `SpecificInformation` carries a
    /// `SpecificInformationType`, and `1` of those is `CLEAR_BASS`.
    pub enum EqBandInformationType, Unknown {
        NoInformation = 0x00,
        Hz = 0x01,
        Khz = 0x02,
        SpecificInformation = 0x10,
    }
}

byte_enum! {
    /// The value of the DSEE setting (`UpscalingSettingType` `AUTO_OFF`).
    pub enum DseeSetting, Unknown {
        Off = 0x00,
        Auto = 0x01,
    }
}

byte_enum! {
    /// The connection-quality priority setting (`E6 01`).
    pub enum ConnectionMode, Unknown {
        SoundQualityPrior = 0x00,
        ConnectionQualityPrior = 0x01,
    }
}

byte_enum! {
    /// `AutoPowerOffElementId`: one entry of the auto-power-off table. The reply to a read
    /// carries two of them, the one in force and the timer remembered for when it is on.
    pub enum AutoPowerOffElementId, Unknown {
        Minutes5 = 0x00,
        Minutes30 = 0x01,
        Minutes60 = 0x02,
        Minutes180 = 0x03,
        WhenRemovedFromEars = 0x10,
        Disable = 0x11,
    }
}

byte_enum! {
    /// Speak-to-Chat sensitivity.
    pub enum StcSensitivity, Unknown {
        Auto = 0x00,
        High = 0x01,
        Low = 0x02,
    }
}

byte_enum! {
    /// `ModeOutTime`: how long Speak-to-Chat stays in talking mode after speech stops.
    pub enum ModeOutTime, Unknown {
        Fast = 0x00,
        Mid = 0x01,
        Slow = 0x02,
        None = 0x03,
    }
}

byte_enum! {
    /// `AssignableSettingsPreset`: what a button or touch sensor is assigned to.
    pub enum AssignableSettingsPreset, Unknown {
        AmbientSoundControl = 0x00,
        VolumeControl = 0x10,
        PlaybackControl = 0x20,
        VoiceRecognition = 0x30,
        GoogleAssistant = 0x31,
        AmazonAlexa = 0x32,
        TencentXiaowei = 0x33,
        NoFunction = 0xff,
    }
}

byte_enum! {
    /// `GsSettingType`: whether a general-setting slot is a switch or a list.
    pub enum GsSettingType, Unknown {
        Boolean = 0x01,
        List = 0x02,
    }
}

byte_enum! {
    /// `GsStringFormat`: whether a general-setting string is literal text or the name of a
    /// title the app knows (see [`GsTitle`](super::GsTitle)).
    pub enum GsStringFormat, Unknown {
        RawName = 0x01,
        EnumName = 0x02,
    }
}

byte_enum! {
    /// `ModelSeries`, from the `05 03` device-info reply.
    pub enum ModelSeries, Unknown {
        None = 0x00,
        ExtraBass = 0x10,
        Hear = 0x20,
        Premium = 0x30,
        Sports = 0x40,
        Casual = 0x50,
    }
}

byte_enum! {
    /// `MdrLanguage`: the language the host tells the headset to localise its names in,
    /// and the one voice guidance speaks.
    pub enum MdrLanguage, Unknown {
        Undefined = 0x00,
        English = 0x01,
        French = 0x02,
        German = 0x03,
        Spanish = 0x04,
        Italian = 0x05,
        Portuguese = 0x06,
        Dutch = 0x07,
        Swedish = 0x08,
        Finnish = 0x09,
        Russian = 0x0a,
        Japanese = 0x0b,
        ChineseSimplified = 0x0c,
        BrazilianPortuguese = 0x0d,
        ChineseTraditional = 0x0e,
        Korean = 0x0f,
        Turkish = 0x10,
    }
}

byte_enum! {
    /// `AlertMessageType`: why the headset is asking, or telling.
    pub enum AlertMessageType, Unknown {
        DisconnectDueToConnectionModeChange = 0x01,
        DisconnectDueToKeyAssignChange = 0x02,
        NeedDisconnectionForFwUpdate = 0x03,
        GoogleAssistantNowAvailable = 0x04,
        DualVoiceAssistantUnavailable = 0x05,
        DisconnectDueToMultipointOn = 0x06,
        DisconnectDueToMultipointOff = 0x07,
        BatteryUseIncreasesWithEqAndDsee = 0x08,
    }
}

byte_enum! {
    /// The pairing mode byte of `33|35 01` (the app's inquiry-scan flag): whether the headset
    /// is accepting new pairings. Not seen on a real headset.
    pub enum PairingMode, Unknown {
        Normal = 0x00,
        InquiryScan = 0x01,
    }
}

byte_enum! {
    /// The last byte of the `31 01` pairing capability: whether the headset can do file
    /// transfer over the link. **`00` is possible, `01` impossible.**
    pub enum FileTransferSupport, Unknown {
        Possible = 0x00,
        Impossible = 0x01,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// `from_raw` and `raw` are inverses over every byte, for every enum.
    #[test]
    fn every_byte_round_trips() {
        for raw in 0..=u8::MAX {
            assert_eq!(CommonStatus::from_raw(raw).raw(), raw);
            assert_eq!(OnOff::from_raw(raw).raw(), raw);
            assert_eq!(FunctionType::from_raw(raw).raw(), raw);
            assert_eq!(BatteryChargingStatus::from_raw(raw).raw(), raw);
            assert_eq!(AudioCodec::from_raw(raw).raw(), raw);
            assert_eq!(NcAsmEffect::from_raw(raw).raw(), raw);
            assert_eq!(EqPresetId::from_raw(raw).raw(), raw);
            assert_eq!(AutoPowerOffElementId::from_raw(raw).raw(), raw);
            assert_eq!(MdrLanguage::from_raw(raw).raw(), raw);
            assert_eq!(AssignableSettingsPreset::from_raw(raw).raw(), raw);
            assert_eq!(ModelSeries::from_raw(raw).raw(), raw);
            assert_eq!(PairingMode::from_raw(raw).raw(), raw);
            assert_eq!(FileTransferSupport::from_raw(raw).raw(), raw);
        }
    }

    /// The polarity that bites: `00` is enabled.
    #[test]
    fn common_status_zero_is_enable() {
        assert_eq!(CommonStatus::from_raw(0x00), CommonStatus::Enable);
        assert_eq!(CommonStatus::from_raw(0x01), CommonStatus::Disable);
        assert_eq!(CommonStatus::from_raw(0xff), CommonStatus::OutOfRange);
        assert_eq!(CommonStatus::from_raw(0x02), CommonStatus::Unknown(2));
    }

    #[test]
    fn sonys_own_catch_alls_are_named_variants() {
        assert_eq!(AudioCodec::from_raw(0xff), AudioCodec::Other);
        assert_eq!(AudioCodec::from_raw(0x30), AudioCodec::Unknown(0x30));
        assert_eq!(
            BatteryChargingStatus::from_raw(0xf0),
            BatteryChargingStatus::Unknown
        );
        assert_eq!(
            BatteryChargingStatus::from_raw(0x02),
            BatteryChargingStatus::Other(2)
        );
    }
}
